//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectExporter.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObjectExporter.Test.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {  
        ///   &quot;Id&quot;:&quot;1ae15a81-0962-467d-9587-62060ba165cd&quot;,
        ///   &quot;Name&quot;:&quot;Tomas&quot;,
        ///   &quot;Age&quot;:22,
        ///   &quot;BirthDay&quot;:&quot;2015-02-28T01:09:54.4346501-06:00&quot;,
        ///   &quot;Wage&quot;:14.5,
        ///   &quot;Height&quot;:122.6,
        ///   &quot;Weight&quot;:142.0,
        ///   &quot;MiddleInitial&quot;:&quot;A&quot;,
        ///   &quot;IsLegalAge&quot;:true,
        ///   &quot;Children&quot;:[  
        ///      {  
        ///         &quot;Id&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,
        ///         &quot;Name&quot;:&quot;Susan&quot;,
        ///         &quot;Age&quot;:2,
        ///         &quot;BirthDay&quot;:&quot;2015-01-01T00:00:00&quot;,
        ///         &quot;Wage&quot;:0.0,
        ///         &quot;Height&quot;:193.36,
        ///         &quot;Weight&quot;:70.05,
        ///         &quot;MiddleIn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CurrentCustomerObject {
            get {
                return ResourceManager.GetString("CurrentCustomerObject", resourceCulture);
            }
        }
    }
}
